### ISSUE TITLE
New hook: afterRemoteError

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-remoting#189]
Consider the use case described in https://github.com/strongloop/loopback-datasource-juggler/pull/545

> 1. in beforeRemote('create', ...) uploaded files (multipart/form-data) are handled
> 2. this adds the stored filename/path to ctx.args.data so the model will save this
> 3. however, the model appears to be invalid for some reason (unrelated to the uploaded file)
> 4. now, validation fails and there's no way to purge the now orphaned uploaded file from storage/disk

We should add a new hook triggered whenever a remote request fails, so that users can clean up any resources allocated in "beforeRemote" hook.

**Tasks**

 - [x] #190 implementation in strong-remoting
 - [x] https://github.com/strongloop/loopback/pull/1272 implementation in loopback
 - [ ] Update the documentation

**Comment by ritch** [comment]
Good idea...

**Comment by bajtos** [comment]
See #190 for the strong-remoting part. I need to implement `Model.afterRemoteError` in loopback once #190 is landed.

**Comment by bajtos** [comment]
I have updated the documentation page http://docs.strongloop.com/display/LB/Remote+hooks and described the new `afterRemoteError` hook. @crandmck please review the page and edit as you like.

I am closing this issue as resolved.
